### ISSUE TITLE
Meteor add xolvio:cucumber ERROR

### ISSUE THREAD

**Issue by charue808** [xolvio/meteor-cucumber#214]
Hello,

Received this error after running meteor add xolvio:cucumber

cgum@cgum-NC10-N110:~/Projects/Personal/twitterTest2$ meteor add xolvio:cucumber
 => Errors while adding packages:             
                                              
While checking for xolvio:cucumber@0.14.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your
platform.

Thanks! Looking forward to checking out the updates!

**Comment by samhatoum** [comment]
oh that's odd. Which OS are you on?

**Comment by charue808** [comment]
Ubuntu 14.04.3

Yeah never had this issue before..I'll try some update upgrades on my end

**Comment by samhatoum** [comment]
I already released it for linux. Odd. Let me know how you get on and I'll try to help

**Comment by myknbani** [comment]
Same issue for Windows, a friend of mine can't add this package after upgrading to 1.2.

However it works fine on my Netrunner/Arch machine.

```
xolvio:cucumber                     0.14.1  CucumberJS for Velocity

                                              
* New versions of these packages are available! Run 'meteor update' to try to update those packages to their latest
  versions. If your packages cannot be updated further, try typing `meteor add <package>@<newVersion>` to see more
  information.

$ meteor --version
Meteor 1.2.0.1
```

**Comment by charue808** [comment]
Just a quick update . Hopefully someone can shed some light on this problem. Still receiving error message: No Compatible binary build found. Running Meteor 1.2.0.2 on Ubuntu 14.04

I updated meteor to 1.2.0.2 on windows 8.1 and it also gave me the error: No Compatible binary build found. I experimented with meteor add xolvio:cucumber@=0.13.8 and that works but I can't upgrade it.

**Comment by samhatoum** [comment]
I will bump the version and try to release a new binary later today.

**Comment by charue808** [comment]
Awesome thank you!!

**Comment by samhatoum** [comment]
version 0.14.2 has been published for all platforms. Give that a try and let me know.

**Comment by abernix** [comment]
I'm on Mac OS X 10.10.15.  I saw this ticket earlier this week while I was looking at other issues – now this just started happening to me today when I ran `meteor update` (I was previously on `xolvio:cucumber@0.14.1` before this):

```
$ meteor update
This project is already at Meteor 1.2.0.2, the latest release.
=> Errors while upgrading packages:           
                                              
While checking for xolvio:cucumber@0.14.6:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

My `meteor show` gives this:
```
$ meteor show xolvio:cucumber
Package: xolvio:cucumber@0.14.6               
Maintainers: samhatoum, xolvio                
Git: https://github.com/xolvio/meteor-cucumber.git

/* abernix snipped */
                                              
Recent versions:                              
  0.14.2  October 1st, 2015                   
  0.14.3  October 1st, 2015
  0.14.4  October 1st, 2015
  0.14.5  October 1st, 2015
  0.14.6  October 1st, 2015
```

**Comment by LikeJasper** [comment]
Also getting this on Mac OS X 10.10.5 trying to update to 0.14.6 (was on 0.14.1 before update, updated fine to 0.14.5).

**Comment by samhatoum** [comment]
I need to automate this!

Try now :)

**Comment by abernix** [comment]
Hehehe.  Yes, all good now.

I like the aggressive release schedule for this package today! :wink:

Thanks for all your great work.

**Comment by LikeJasper** [comment]
Great, thank you! For some reason I had to use `meteor add xolvio:cucumber@0.14.6` explicitly though, as `meteor update` gave me this:
    This project is already at Meteor 1.2.0.2, the latest release.
    Your top-level dependencies are at their latest compatible
    versions.
    
    The following top-level dependencies were not updated to the very
    latest version available:
     * xolvio:cucumber 0.14.5 (0.14.6 is available)
    
    Newer versions of the following indirect dependencies are
    available:
     * practicalmeteor:chai 1.9.2_3 (2.1.0_1 is available)
     * practicalmeteor:loglevel 1.1.0_3 (1.2.0_2 is available)
     * sanjo:meteor-files-helpers 1.1.0_7 (1.2.0_1 is available)
    To update one or more of these packages, pass their names to
    `meteor update`.
and `meteor update xolvio:cucumber` gave me this:
    The specified packages are at their latest compatible versions.

**Comment by Sanjo** [comment]
@LikeJasper Try `meteor refresh` maybe?

**Comment by Sanjo** [comment]
@LikeJasper I think that's because you have pinned the version in .meteor/packages. Remove the version from there and updates should work again.

**Comment by LikeJasper** [comment]
Ah of course, when I updated to 0.14.5. Thanks so much.
